version: "3.8"
services:

  frontend:
    build:
      context: frontend
      target: local
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json

  backend:
    build:
      context: backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
      - ./backend/tests:/app/tests
